inmakes_product_folder/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

inmakes_product_folder/movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inmakes_product_folder/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

inmakes_product_folder/movieproject/movieapp/forms.py
from django import forms
from.models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

inmakes_product_folder/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={'key':movie}
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'key':movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,"add.html")
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{"key1":form,"key2":movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

inmakes_product_folder/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name" required>
    <input type="text" name="desc" placeholder="Enter the movie description" required>
    <input type="text" name="year" placeholder="Enter the movie year" required>
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

inmakes_product_folder/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand"  href=""><b>Online Movie Stories</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="btn btn-danger" href="{% url 'movieapp:add_movie' %}">Add movie<span class="sr-only">(current)</span></a>
      </li>
      </div>
      <div class=col-12 col-sm-12 col-md-12 col-lg-12>
      <li class="nav-item">
        <a class="btn btn-warning" href="{% url 'movieapp:index' %}">Home</a>
      </li>
      </div>
    </ul>
  <!--</div>-->
</nav>
{% block body %}
{% endblock %}
</body>
</html>

inmakes_product_folder/movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie ?
    <input type="submit">
</form>

inmakes_product_folder/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{key.img.url}}" width="300" height="300">
        </div>
<div class="col-md-6">
    <h3 style="color:red;">{{key.name}}</h3>
    <h6>{{key.desc}}</h6>
    <h6>{{key.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' key.id %}">Update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' key.id %}">Delete</a>

</div>
    </div>
</div>
{% endblock %}

inmakes_product_folder/movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{key1.as_p}}
    <input type="submit">
</form>

inmakes_product_folder/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row mx_auto">
        {% for i in key %}
<!--        <div class="col-md-3">-->
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
<!--            <div class="card" style="width: 18rem;">-->
                <div class="card text-center" style="min-width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="300px" height="242px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Movie details</a>
  </div>
</div>
                <br>
        </div>

        {% endfor %}

    </div>

</div>

{% endblock %}

inmakes_product_folder/movieproject/templates/moviecreate.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name">
    <input type="text" name="desc" placeholder="Enter the movie description">
    <input type="text" name="year" placeholder="Enter the movie year">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}